### PR TITLE
Python 3.6 Updates

### PR DESCRIPTION
**Pull request by nmiles2718**
#### Docker updates:
- Build scripts have been updated to use Python 3.6
- Amazon linux image has been updated to use[ amazonlinux:2018.03](https://hub.docker.com/_/amazonlinux?tab=tags&page=1&ordering=last_updated). 

#### `process.py` updates:
- The `print` function has been replaced with python's [logging module](https://docs.python.org/3.6/library/logging.html).
- The module has been refactored to improve readability. 
  - This is purely an aesthetic choice and I am happy to revert to original if you wish.
- The generated PNG and catalog for each image are now stored in the same directory
  - Directory names correspond to each input file's [ipppssoot](https://archive.stsci.edu/hlsp/ipppssoot.html)
- Implemented automatic creation of a 2D Gaussian kernel using `astropy.convolution`
  - The previous kernel still remains as a global variable, but it is not used 
- New functionality has been added to clean up the `/tmp` directory used by each Lambda function. 
   - When many invocations occurs in a short period of time, Lambda may allow `/tmp` to persist between successive invocations. This leads to an `OSError` raised by python as the disk space of the Lambda server will eventually fill up and cause any successive calls to fail.

#### Testing:
I generated a simple test event for the Lambda function in the AWS Lambda Console using a WFC3/IR image I uploaded to my `s3` bucket. I tested an invocation end-to-end and it ran to completion and the expected output files were created.

Closes issue #4

### CODE REVIEW

**Comment by arfon** [comment]
😻 this looks great! / cc @ivastar for a quick 👀 too.

**Comment by ivastar** [comment]
This looks great @nmiles2718! I'd be happy to just merge this. If you would rather that I tested it, I can probably make time for it next week.

**Comment by nmiles2718** [comment]
I think it would be best to have you run through it real quick just to be safe 😄

**Comment by arfon** [comment]
@nmiles2718 - I'm happy to try and take this for a spin. Will something like the command in the existing docs work to test this? e.g.

```
$ docker run --rm -e AWS_ACCESS_KEY_ID='XXXXXXXXX' -e AWS_SECRET_ACCESS_KEY='XXXXXXXXX' -v "$PWD":/var/task lambci/lambda:python2.7 process.handler '{"s3_output_bucket": "dsmo-lambda-test-outputs", "fits_s3_key":"hst/public/icsc/icsca0voq/icsca0voq_drz.fits", "fits_s3_bucket":"stpubdata"}'
```

**Comment by nmiles2718** [comment]
Not sure, I've never used docker to test a lambda function locally and I still don't have it installed on my computer. I think it's worth trying though, but just make sure to change `lambci/lambda:python2.7` to `lambci/lambda:python3.6` 👍

**Comment by arfon** [comment]
So this looks to be mostly working for me. I get sources detected:
icsca0voq

...but also an error at the end:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/var/lang/lib/python3.6/shutil.py", line 475, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/matplotlib-mixg0s92'
```

Any ideas what this might be @nmiles2718?

**Comment by nmiles2718** [comment]
Hmmm, that's odd. My guess is that when testing things locally, something else has gone in and cleaned the `/tmp` directory prior to `shutil.rmtree` and so it tried to delete something that had already been deleted. 

The weird part is that I specifically set [ignore_errors=True](https://github.com/spacetelescope/astropy-sep-lambda/blob/15da7de9d4565a771ab0cdb579161b5c354768f1/process.py#L297) to avoid this behavior. It is related to a known issue with `shutil.rmtree()` and given the discussion had [here](https://bugs.python.org/issue29699), I think the optimal solution will be for me to just wrap that function call in a `try: ... except FileNotFoundError: pass`. Unless you have a better idea for recursively removing files without knowing the directory tree structure a priori?

**Comment by arfon** [comment]
> Unless you have a better idea for recursively removing files without knowing the directory tree structure a prior?

Not really :-). Your suggested solution sounds reasonable, especially as this is just cleanup at the end.

**Comment by arfon** [comment]
Actually we don't need to rescue this. If you change the function to this then things work great:

```
def clean_up(dirname="./tmp"):
    """ Delete all files created and stored in the lambda tmp directory

    Lambda can only store so much data in tmp and when many function
    invocations occur in a short period of time, memory will sometimes persist
    innovcations and so to avoid filling up the maximum allowable memory for
    a function, we need to delete the files we stored

    Parameters
    ----------
    dirname : str
        path to /tmp on lambda function

    Returns
    -------

    """
    shutil.rmtree(dirname, ignore_errors=True)
```

Specifically, the path should be `"./tmp"` not `"/tmp"`

**Comment by nmiles2718** [comment]
Hmm, I wonder if we are running into differences between how the lambda function is run locally vs how it is run on AWS? It seems odd that `./tmp` works and `/tmp` would not. On AWS, I'm like 98% sure that everything on Lambda is run from the root directory and so `./tmp`=`/tmp`. 

I have no clue how docker tests the lambda function locally, but my guess is it mimics the structure Lambda uses for a function just not from the root directory? If so, then we lose the equivalence between `./tmp/` and `/tmp` and I think this is what causes the error you saw earlier (based on your last comment).

In any case, since I know everything is run in the root directory on AWS and `./tmp`=`/tmp` it should be fine to update everything to just use `./tmp`. Just to be sure though, I'm going to rebuild the lambda, deploy it to AWS, then invoke it. I would hate to have things run locally, but not in the cloud! lol

**Comment by nmiles2718** [comment]
Ok, so I think that 2% of me was correct after all. After updating the dirname to be `./tmp` instead of `/tmp`, the function executes once and then fails in the next invocation because the previous catalog is still present in that `/tmp` directory indicating that `./tmp` != `/tmp`, which implies that Lambda does not execute in the root directory.

Indeed, after finding the correct incantation for google I finally got a [useful post](https://medium.com/@jbirdvegas/lambdas-default-environment-variables-for-python-3-6-with-role-attached-9ef107967e15) that examined lambda's runtime structure in python3.6. The definitions for each of the environment variables may be found [here](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime). This leads me to believe that whatever structure docker makes is what caused the error at the end and so we can probably safely ignore the error.

**Comment by arfon** [comment]
:zap: thanks for debugging this @nmiles2718!

**Pull request merged**
